import dotenv from "dotenv";
import mongoose from "mongoose";
import Listing from "./models/listing.model.js";

dotenv.config();

// Connect to MongoDB
mongoose
    .connect(process.env.MONGO_URL)
    .then(() => {
        console.log("Connected to MongoDB Successfully!");
    })
    .catch((err) => {
        console.log("MongoDB connection error:", err);
        process.exit(1);
    });

// Property images paths (using generated images and placeholders)
const propertyImages = {
    mumbaiApt1: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    mumbaiApt2: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
    mumbaiPenth: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
    bangaloreVilla1: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    bangaloreVilla2: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    bangaloreApt: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
    delhiFlat: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800",
    puneVilla: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
    hyderabadHome: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800",
    chennaiApt: "https://images.unsplash.com/photo-1600573472605-0c6c9b5f4f9f?w=800",
    kolkataApt: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
    studioApt: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800",
};

// Sample user ID - you'll need to replace this with an actual user ID from your database
// For now, we'll use a placeholder
const SAMPLE_USER_ID = "691a44f14f8fc47734f5300c"; // Real user ID from database

const indianProperties = [
    // Mumbai Properties (8)
    {
        name: "Luxury 3 BHK in Bandra West",
        description: "Premium apartment with stunning sea view, modern amenities, gym, swimming pool, 24/7 security. Located in the heart of Bandra West with easy access to shopping and dining.",
        address: "Bandra West, Mumbai, Maharashtra 400050",
        regularPrice: 25000000,
        discountPrice: 24000000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.mumbaiApt1],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Modern 2 BHK Apartment in Andheri",
        description: "Well-ventilated apartment close to metro station, shopping malls, and IT parks. Perfect for working professionals.",
        address: "Andheri East, Mumbai, Maharashtra 400069",
        regularPrice: 65000,
        discountPrice: 60000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: true,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.mumbaiApt2],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Spacious 4 BHK Penthouse Powai",
        description: "Ultra-luxury penthouse with private terrace, modular kitchen, and panoramic city views. Premium gated community.",
        address: "Powai, Mumbai, Maharashtra 400076",
        regularPrice: 55000000,
        discountPrice: 55000000,
        bathrooms: 4,
        bedrooms: 4,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.mumbaiPenth],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Cozy 1 BHK in Juhu",
        description: "Affordable apartment near Juhu beach, perfect for singles or couples. Close to restaurants and entertainment.",
        address: "Juhu, Mumbai, Maharashtra 400049",
        regularPrice: 35000,
        discountPrice: 32000,
        bathrooms: 1,
        bedrooms: 1,
        furnished: false,
        parking: false,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.mumbaiApt1],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Premium 3 BHK Worli Sea Facing",
        description: "Luxurious sea-facing apartment with world-class amenities, clubhouse, and concierge services.",
        address: "Worli, Mumbai, Maharashtra 400018",
        regularPrice: 45000000,
        discountPrice: 45000000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.mumbaiPenth],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Studio Apartment Malad",
        description: "Compact and efficient studio perfect for young professionals. Well-connected by road and rail.",
        address: "Malad West, Mumbai, Maharashtra 400064",
        regularPrice: 18000,
        discountPrice: 18000,
        bathrooms: 1,
        bedrooms: 1,
        furnished: true,
        parking: false,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.studioApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "2 BHK in Thane West",
        description: "Spacious apartment in peaceful locality with parks, schools, and hospitals nearby.",
        address: "Thane West, Thane, Maharashtra 400601",
        regularPrice: 9500000,
        discountPrice: 9000000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: false,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.mumbaiApt2],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Elegant 3 BHK Santacruz",
        description: "Well-maintained apartment near airport, ideal for frequent travelers. Modern amenities included.",
        address: "Santacruz East, Mumbai, Maharashtra 400055",
        regularPrice: 75000,
        discountPrice: 75000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.mumbaiApt1],
        userRef: SAMPLE_USER_ID,
    },

    // Bangalore Properties (8)
    {
        name: "Contemporary Villa in Whitefield",
        description: "Modern 4 BHK villa with private garden, perfect for IT professionals. Close to tech parks and international schools.",
        address: "Whitefield, Bangalore, Karnataka 560066",
        regularPrice: 125000,
        discountPrice: 115000,
        bathrooms: 4,
        bedrooms: 4,
        furnished: true,
        parking: true,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.bangaloreVilla1],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Stylish 2 BHK Koramangala",
        description: "Trendy apartment in vibrant Koramangala, walking distance to cafes, pubs, and shopping areas.",
        address: "Koramangala 5th Block, Bangalore, Karnataka 560095",
        regularPrice: 15000000,
        discountPrice: 14500000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.bangaloreApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Spacious 3 BHK HSR Layout",
        description: "Family-friendly apartment with excellent schools and parks nearby. Safe and secure gated community.",
        address: "HSR Layout Sector 2, Bangalore, Karnataka 560102",
        regularPrice: 55000,
        discountPrice: 55000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: false,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.bangaloreVilla2],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Luxury Villa Indiranagar",
        description: "Independent villa with modern architecture, landscaped garden, and premium finishes throughout.",
        address: "Indiranagar, Bangalore, Karnataka 560038",
        regularPrice: 35000000,
        discountPrice: 35000000,
        bathrooms: 4,
        bedrooms: 4,
        furnished: false,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.bangaloreVilla1],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Modern 1 BHK Electronic City",
        description: "Affordable apartment near tech parks, perfect for IT professionals. Good connectivity and amenities.",
        address: "Electronic City Phase 1, Bangalore, Karnataka 560100",
        regularPrice: 22000,
        discountPrice: 20000,
        bathrooms: 1,
        bedrooms: 1,
        furnished: true,
        parking: false,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.bangaloreApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Penthouse in Jayanagar",
        description: "Exclusive penthouse with rooftop garden, gym, and entertainment area. Prime South Bangalore location.",
        address: "Jayanagar 4th Block, Bangalore, Karnataka 560011",
        regularPrice: 28000000,
        discountPrice: 27000000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.bangaloreVilla2],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "2 BHK Bellandur",
        description: "Well-connected apartment near Outer Ring Road, close to IT corridor and shopping malls.",
        address: "Bellandur, Bangalore, Karnataka 560103",
        regularPrice: 35000,
        discountPrice: 35000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: false,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.bangaloreApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "5 BHK Duplex Sarjapur Road",
        description: "Massive duplex villa with home theater, gym, and swimming pool. Ultra-luxury living.",
        address: "Sarjapur Road, Bangalore, Karnataka 560035",
        regularPrice: 45000000,
        discountPrice: 45000000,
        bathrooms: 5,
        bedrooms: 5,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.bangaloreVilla1],
        userRef: SAMPLE_USER_ID,
    },

    // Delhi NCR Properties (7)
    {
        name: "Elegant 3 BHK Vasant Vihar",
        description: "Premium apartment in posh South Delhi locality, near diplomatic enclave and premium shopping.",
        address: "Vasant Vihar, New Delhi, Delhi 110057",
        regularPrice: 35000000,
        discountPrice: 33500000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.delhiFlat],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Modern 2 BHK Gurgaon",
        description: "Contemporary apartment in cyber city area, walking distance to offices and metro station.",
        address: "Cyber City, Gurgaon, Haryana 122002",
        regularPrice: 45000,
        discountPrice: 42000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: true,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.delhiFlat],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Spacious 4 BHK Greater Noida",
        description: "Family home with large balconies, children's play area, and 24/7 security in premium township.",
        address: "Greater Noida West, Uttar Pradesh 201306",
        regularPrice: 12000000,
        discountPrice: 12000000,
        bathrooms: 3,
        bedrooms: 4,
        furnished: false,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.puneVilla],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Luxury Apartment Dwarka",
        description: "Well-designed apartment near airport, metro connectivity, and shopping complexes.",
        address: "Dwarka Sector 10, New Delhi, Delhi 110075",
        regularPrice: 28000,
        discountPrice: 28000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: false,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.delhiFlat],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Studio Flat Noida Sector 62",
        description: "Compact studio perfect for IT professionals working in tech hub area.",
        address: "Sector 62, Noida, Uttar Pradesh 201309",
        regularPrice: 15000,
        discountPrice: 14000,
        bathrooms: 1,
        bedrooms: 1,
        furnished: true,
        parking: false,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.studioApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "3 BHK Saket Premium",
        description: "Upscale apartment in South Delhi with mall, metro, and premium hospitals nearby.",
        address: "Saket, New Delhi, Delhi 110017",
        regularPrice: 22000000,
        discountPrice: 21000000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.delhiFlat],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Independent House Faridabad",
        description: "Standalone villa with parking for 3 cars, garden, and terrace. Peaceful residential area.",
        address: "Sector 15, Faridabad, Haryana 121007",
        regularPrice: 85000,
        discountPrice: 85000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: false,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.puneVilla],
        userRef: SAMPLE_USER_ID,
    },

    // Pune Properties (5)
    {
        name: "Premium Villa Koregaon Park",
        description: "Luxurious villa in upscale Koregaon Park, near restaurants, cafes, and German Bakery.",
        address: "Koregaon Park, Pune, Maharashtra 411001",
        regularPrice: 95000,
        discountPrice: 90000,
        bathrooms: 4,
        bedrooms: 4,
        furnished: true,
        parking: true,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.puneVilla],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "IT Professional 2 BHK Hinjewadi",
        description: "Modern apartment near IT parks, perfect for techies. Gym, pool, and clubhouse included.",
        address: "Hinjewadi Phase 1, Pune, Maharashtra 411057",
        regularPrice: 8500000,
        discountPrice: 8000000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.bangaloreApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Cozy 1 BHK Viman Nagar",
        description: "Affordable flat near airport, shopping malls, and Phoenix Market City.",
        address: "Viman Nagar, Pune, Maharashtra 411014",
        regularPrice: 18000,
        discountPrice: 18000,
        bathrooms: 1,
        bedrooms: 1,
        furnished: false,
        parking: false,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.puneVilla],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "3 BHK Aundh Premium",
        description: "Spacious apartment in prime Aundh location with excellent schools and hospitals.",
        address: "Aundh, Pune, Maharashtra 411007",
        regularPrice: 14000000,
        discountPrice: 14000000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: false,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.puneVilla],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Penthouse Baner Road",
        description: "Luxurious penthouse with terrace garden, modular kitchen, and premium amenities.",
        address: "Baner, Pune, Maharashtra 411045",
        regularPrice: 18000000,
        discountPrice: 17500000,
        bathrooms: 3,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.bangaloreVilla2],
        userRef: SAMPLE_USER_ID,
    },

    // Hyderabad Properties (4)
    {
        name: "Modern 2 BHK Gachibowli",
        description: "Tech-hub apartment close to major IT companies, metro station, and shopping centers.",
        address: "Gachibowli, Hyderabad, Telangana 500032",
        regularPrice: 32000,
        discountPrice: 30000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: true,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.hyderabadHome],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Luxury Villa Banjara Hills",
        description: "Premium independent villa in posh locality with swimming pool and landscaped garden.",
        address: "Banjara Hills Road No. 12, Hyderabad, Telangana 500034",
        regularPrice: 42000000,
        discountPrice: 42000000,
        bathrooms: 4,
        bedrooms: 4,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        imageUrls: [propertyImages.bangaloreVilla1],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "3 BHK Hitech City",
        description: "Well-maintained apartment in prime IT corridor, close to Cyber Towers and shopping malls.",
        address: "Hitech City, Hyderabad, Telangana 500081",
        regularPrice: 55000,
        discountPrice: 55000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: false,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.hyderabadHome],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Spacious 4 BHK Kondapur",
        description: "Family-friendly apartment with children's play area, gym, and swimming pool.",
        address: "Kondapur, Hyderabad, Telangana 500084",
        regularPrice: 11000000,
        discountPrice: 10500000,
        bathrooms: 3,
        bedrooms: 4,
        furnished: false,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.bangaloreVilla2],
        userRef: SAMPLE_USER_ID,
    },

    // Chennai & Kolkata Properties (3)
    {
        name: "2 BHK Anna Nagar Chennai",
        description: "Central location apartment with easy access to metro, hospitals, and educational institutions.",
        address: "Anna Nagar West, Chennai, Tamil Nadu 600040",
        regularPrice: 9000000,
        discountPrice: 8700000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: false,
        parking: true,
        type: "sale",
        offer: true,
        imageUrls: [propertyImages.chennaiApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "3 BHK Salt Lake Kolkata",
        description: "Spacious apartment in well-planned township with parks, shopping, and good connectivity.",
        address: "Salt Lake Sector 5, Kolkata, West Bengal 700091",
        regularPrice: 35000,
        discountPrice: 35000,
        bathrooms: 2,
        bedrooms: 3,
        furnished: true,
        parking: true,
        type: "rent",
        offer: false,
        imageUrls: [propertyImages.kolkataApt],
        userRef: SAMPLE_USER_ID,
    },
    {
        name: "Elegant 2 BHK T Nagar Chennai",
        description: "Prime location near shopping district, temples, and public transport. Traditional yet modern.",
        address: "T Nagar, Chennai, Tamil Nadu 600017",
        regularPrice: 28000,
        discountPrice: 26000,
        bathrooms: 2,
        bedrooms: 2,
        furnished: true,
        parking: false,
        type: "rent",
        offer: true,
        imageUrls: [propertyImages.chennaiApt],
        userRef: SAMPLE_USER_ID,
    },
];

// Function to seed the database
const seedDatabase = async () => {
    try {
        // Clear existing listings (optional - comment out if you want to keep existing data)
        console.log("Clearing existing listings...");
        await Listing.deleteMany({});
        console.log("Existing listings cleared.");

        // Insert new listings
        console.log("Adding new property listings...");
        await Listing.insertMany(indianProperties);
        console.log(
            `✅ Successfully added ${indianProperties.length} Indian property listings!`
        );

        // Show summary
        console.log("\n📊 Summary:");
        console.log(`Total Properties: ${indianProperties.length}`);
        console.log(
            `For Sale: ${indianProperties.filter((p) => p.type === "sale").length
            }`
        );
        console.log(
            `For Rent: ${indianProperties.filter((p) => p.type === "rent").length
            }`
        );
        console.log(
            `With Offers: ${indianProperties.filter((p) => p.offer).length}`
        );

        // Exit
        mongoose.connection.close();
        console.log("\n✨ Database seeding completed successfully!");
        process.exit(0);
    } catch (error) {
        console.error("❌ Error seeding database:", error);
        mongoose.connection.close();
        process.exit(1);
    }
};

// Run the seed function
seedDatabase();
